export { ErrorPage } from './error-page/ErrorPage'
export { MainPage } from './main-page/MainPage'
export { NotFoundPage } from './not-found-page/NotFoundPage'
export { RegisterPage as SignInPage } from './register-page/RegisterPage'
export { ProductPage } from './product-page/ProductPage'
export { ProductListPage } from './product-list-page/ProductListPage'
export { CreateProductPage } from './product-editor-page/CreateProductPage'
