export { default as Home } from './Home.svg?react'
export { default as Product } from './Product.svg?react'
export { default as Arrow } from './arrow.svg?react'
export { default as Logout } from './logout.svg?react'
export { default as Up } from './up.svg?react'
export { default as Down } from './down.svg?react'
